# Generated by Django 3.1.4 on 2020-12-24 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='sir_name',
        ),
    ]
